name: Build and Release

on:
  push:
    tags:
      - 'v*'  # 触发条件：当推送的标签以 v 开头时
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up a language runtime if needed (e.g., Node.js, Go, etc.)
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23

    # Build your project
    - name: Build project
      run: |
        make linux ARCH=amd64
        make mac ARCH=amd64
        make windows ARCH=amd64
        make linux ARCH=arm64
        make mac ARCH=arm64
        make windows ARCH=arm64

    # Create a release
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Upload files
    - name: Upload kv.amd64.appx
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./output/kv.amd64.appx
        asset_name: kv.amd64.appx
        asset_content_type: application/vnd.ms-appx

    - name: Upload kv.amd64.bin
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./output/kv.amd64.bin
        asset_name: kv.amd64.bin
        asset_content_type: application/octet-stream

    - name: Upload kv.amd64.exe
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./output/kv.amd64.exe
        asset_name: kv.amd64.exe
        asset_content_type: application/x-msdownload

    - name: Upload kv.arm64.appx
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./output/kv.arm64.appx
        asset_name: kv.arm64.appx
        asset_content_type: application/vnd.ms-appx

    - name: Upload kv.arm64.bin
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./output/kv.arm64.bin
        asset_name: kv.arm64.bin
        asset_content_type: application/octet-stream

    - name: Upload kv.arm64.exe
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./output/kv.arm64.exe
        asset_name: kv.arm64.exe
        asset_content_type: application/x-msdownload